// Admin Types
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_GIGS_SUCCESS = 'GET_GIGS_SUCCESS';
export const GET_GIGS_FAIL = 'GET_GIGS_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_GIG_SUCCESS = 'DELETE_GIG_SUCCESS';
export const DELETE_GIG_FAIL = 'DELETE_GIG_FAIL'; 